prompt = 'What is the length of link 1?';
d = input(prompt)
prompt = 'What is the length of link 2?';
a = input(prompt)
prompt = 'What is the length of link 4?';
c = input(prompt)
prompt = 'What is the value of gamma?';
y = input(prompt)
prompt = 'What is the value of theta 2?';
T2 = input(prompt)
prompt = 'What is the value of omega 2?';
w2 = input(prompt)
P = a*sind(T2)*sind(y) + (a*cosd(T2) - d)*cosd(y)
Q = -a*sind(T2)*cosd(y) + (a*cosd(T2) - d)*sind(y)
R = -c*sind(y)
S = R - Q
T = 2*P
U = Q + R
T41 = 2*atand((-T + sqrt(T^2 - 4*S*U))/(2*S))
T42 = 2*atand((-T - sqrt(T^2 - 4*S*U))/(2*S))
T31 = T41 + y
T32 = T42 + y + 180
b1 = (a*sind(T2)-c*sind(T41))/(sind(T31))
b2 = (a*sind(T2)-c*sind(T42))/(sind(T32))
w41 = (a*w2*cosd(T2-T31))/(b1 + c*cosd(y))
w42 = (a*w2*cosd(T2-T32))/(b2 + c*cosd(y))
Va = a*w2*(-sind(T2) + 1i*cosd(T2))
Vam = abs(Va)
TVa = radtodeg(angle(Va))
VB41 = c*w41*(-sind(T41) + 1i*cosd(T41))
VB41m = abs(VB41)
TVb41 = radtodeg(angle(VB41))
VB42 = c*w42*(-sind(T42) + 1i*cosd(T42))
VB42m = abs(VB42)
TVb42 = radtodeg(angle(VB42))
Vsl = (-a*w2*sind(T2) + w41*(b1*sind(T31) + c*sind(T41)))/cosd(T31)
Vs2 = (-a*w2*sind(T2) + w42*(b2*sind(T32) + c*sind(T42)))/cosd(T32)